### PR TITLE
Added support for Icecast stream metadata

### PR DESCRIPTION
**Pull request by abuharsky**
full support for icecast metadata, example app also updated

### CODE REVIEW

**Comment by abuharsky** [comment]
maybe only one problem be here:
I have slightly modify project setup by adding to Example app StreamingKit as subproject, but it no problem I think

**Comment by tumtumtum** [comment]
Although this adds Icecast metadata support to the http data source it doesn't integrate well with STKAudioPlayer since the metadata can arrive ahead of when audio is actually played (due to the buffering and queuing nature of STK).

**Comment by abuharsky** [comment]
No, just try to use it with real streams.

Metadata very accurate.

**Comment by abuharsky** [comment]
Maybe you were right for some cases, when buffered data not too small.
I agree, that for this cases metadata may not be synchronized with actual audio.

So, I can research that moment.

**Comment by syrakozz** [comment]
all is good if it keep this project update and active :)

**Comment by alejandroivan** [comment]
I've been trying this modification but it causes the audio to "skip" (a little pause) when metadata arrives. Is it just me?

**Comment by tlenclos** [comment]
What is blocking this PR ? I'm really looking for this feature.

**Comment by prakashdesai** [comment]
@abuharsky App crashing at 

read = [super readIntoBuffer:(_metadataData.mutableBytes + _metadataBytesRead)
                                    withSize:_metadataLength - _metadataBytesRead];

in STKHTTPDataSource.m file

**Comment by iDevelopper** [comment]
@tlenclos , MERCI ! Thanks a lot for added IceCast Metadata to this project. Do you finally know why this PR did not join the master branch?

**Comment by tlenclos** [comment]
@iDevelopper sadly no, and I'm using this in a react-native module so I would love to see this merged one day ^^.

**Comment by iDevelopper** [comment]
Hi @tlenclos , when I activate my audio session, I add an observer for AVAudioSessionInterruptionNotification. However, my handle method is called for AVAudioSessionInterruptionTypeBegan but never for AVAudioSessionInterruptionTypeEnded. And the application do not resume audio after interruption. Any ideas about this? Thanks.

**Comment by iDevelopper** [comment]
Hi @tumtumtum ,

Could you please merge the @tlenclos PR for Icecast metadata, at least for live stream url?

Thanks in advance

**Comment by iDevelopper** [comment]
Superb! Ice cast support works. Tested! Thanks! Do you plan to update cocoa pods with this merge and others? Regards.

**Comment by derpoliuk** [comment]
@iDevelopper you're welcome! I'm waiting for updates from @haritowa in #391 to create and push new version. But if there'll be no response in couple of days, I'll push new version.

**Comment by iDevelopper** [comment]
Ok, thanks again

**Pull request merged**
