### PR TITLE
Added Variable Playback Speed Feature

### PR DESCRIPTION
**Pull request by Dabuk**
Added Playback Speed change feature with sliderUI in exampleApp.
Relevant comments written.

### CODE REVIEW

**Comment by pcbeard** [comment]
I cleaned this patch up a little bit and tested it:

https://github.com/pcbeard/StreamingKit/tree/PlaybackRate

It works, but if you set the audio rate to > 1for a network stream, the audio stops, because obviously it's not arriving at the rate it's being played.

**Comment by Dabuk** [comment]
What network streaming are you referencing to? Live streaming or a media link? If it's a media link it should work because streaming kit is deigned to pull more data off the stream as it is consumed. I have tested it for 2x..works fine..

**Comment by pcbeard** [comment]
Live streaming of course. There's no practical way to speed that up. Perhaps we should only selectively enable if the stream is able to read farther ahead?

**Comment by Sapanesh** [comment]
@pcbeard 
Hi ,
I used your branch..but audio quality decreased after change playback rate.

Please suggest.


Thanks,

**Comment by anandmahajan** [comment]
Hi

@Dabuk @kevinrenskers 

So quality really bad after change playback rate..Can you please help ?
Or any Solution ?

Thanks

**Comment by QB3L** [comment]
I also tested this one and it works like a charm. @tumtumtum can we get it approved and merged?

**Comment by dong136279559** [comment]
I also need the function of rate. Could the author provide help
@tumtumtum

**Pull request closed without merging**
