### PR TITLE
Fixed a SSL Handshaking issue

### LINKED ISSUE #309: Expose SSL settings in STKHTTPDataSource
I had a bunch of issues with `CFNetwork SSLHandshake failed (-9824)` for certain URLs.

After careful inspection of SSL certs and comparing against ones that work, it seems that my server requires Server Name Indicator (SNI) verification. The SSL settings seem to force a null for `kCFStreamSSLPeerName` (see settings defined at https://github.com/tumtumtum/StreamingKit/blob/master/StreamingKit/StreamingKit/STKHTTPDataSource.m#L556)

Would it be possible to get these SSL settings exposed? My temporary workaround is to remove the null for `kCFStreamSSLPeerName` and compile StreamingKit without using CocoaPods, but it would be much cleaner if I could pass in the preferred SSL settings when instantiating StreamingKit.

### PR DESCRIPTION
**Pull request by docterd**
Fixes a SSL Handshake Issue (fixes #309)

### CODE REVIEW

**Comment by patrickjquinn** [comment]
Hey @docterd could you possibly give us a sample case for the issue this fixes?

**Comment by HyanCat** [comment]
Great! It works for me.

**Comment by QB3L** [comment]
This worked for me as well.

**Comment by derpoliuk** [comment]
@docterd thank you for contribution! Please remove `Delete StreamingKit-head.podspec` commit and I'll merge it (I guess this commit didn't fix SSL issue?).

**Comment by docterd** [comment]
@derpoliuk go for it :-)

**Comment by derpoliuk** [comment]
@docterd thank you for update! Merging...

**Pull request merged**
