### PR TITLE
Replace OSSpinLock with os_unfair_lock

### PR DESCRIPTION
**Pull request by michael-yuji**
since OSSpinLock is deprecated in iOS 10.

### CODE REVIEW

**Comment by tumtumtum** [comment]
Hi!

Thank you! I think this is needed but couple of things:

* Your PR has a lot of code formatting/indenting changes - can you split those from the `os_unfair_lock` code (it should be a separate PR)
* We should add a preprocessor check so that we fall back to `OSSpinLock` when using iOS and OSX versions that do not support `os_unfair_lock`

**Comment by michael-yuji** [comment]
Oh my bad, I wasn't aware of the change in formatting.

**Comment by diegostamigni** [comment]
@michael-yuji you sorting this?

**Comment by tumtumtum** [comment]
> @michael-yuji you sorting this?

I think we will need to support OSSpinLock on older operating systems with preprocessor checks? Perhaps define a macro for the lock so that we can use them interchangeably. I'm also not convinced about having two locals (the value and the pointer).

**Comment by diegostamigni** [comment]
Closing this one as now duplicate of #423

**Pull request closed without merging**
